### PR TITLE
User module

### PR DESCRIPTION
**Pull request by mohamednaser**
This branch include these features : 

1- User model with validations 
2- Post model with validations 
3- Comments model with validations 
4- build relations between posts and users 
5- build relations between comments, posts and users.

### CODE REVIEW

**Review by Ispirett — CHANGES_REQUESTED** [review]
# Status Changes Required
Greate work @mohamednaser  you did well thus far.

- [x] *Post*  model should be able to have many comments [see here]
- [ ] **Tests** you should have tests for **Post** **Comment** **User**
- [x] Comment Test [see here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/comment_belongs_to_a_user.png)
and [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/comment_belongs_to_a_post.png)

- [ ] Post test [see here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_belongs_to_a_user.png)
and [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_has_many_comments.png)
- [ ] User tests [see here]
(https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_has_many_comments.png)
- [ ] *Optional* it would have been nice to have a ui to navigate your app.
_many_comments.png)

- [ ] User tests [see here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_posts.png)
and [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_comments.png)

(https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_has_many_comments.png)
- [ ] *Optional* it would have been nice to have a ui to navigate your app.

**Review by Ispirett — CHANGES_REQUESTED** [review]
Status Changes Required :factory: 
Greate work with changes @mohamednaser :100:  but there are still somethings to address.

- [ ] THere should be some tests for User and Post model. [see here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/comment_belongs_to_a_user.png) and [see here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/comment_belongs_to_a_post.png)

**Comment by mohamednaser** [comment]
@Ispirett 

can You please clarify more about tests . do you mean we need to add test cases for User and Post Models using Rspec?

**Comment by Ispirett** [comment]
Hey yes tests for User and Post with rspec

**Review by nikasulo — APPROVED** [review]
# Great work! @mohamednaser 
Please merge and keep moving forward, I wish you the best and see you at the very top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
